### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-odesk#7]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@romankisilenko can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@maurezen many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `50043325`

**Comment by RomanKisilenko** [comment]
@maurezen PR was reviewed and closed, please close the issue.

**Comment by dmarkov** [comment]
@romankisilenko **30 mins** was added to your account, many thanks for your contribution!; +30 added to your rating, current score is: +210
